name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    strategy:
      matrix:
        # Include amd64 on all platforms.
        goos: [windows,linux]
        goarch: [amd64, 386]
        exclude:
          # Exclude i386 on darwin and dragonfly.
          - goarch: 386
            goos: dragonfly
          - goarch: 386
            goos: darwin
        include:
          # BEGIN Other architectures
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: arm64
          # END Other architectures
      fail-fast: false

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show workflow information
        id: get_filename
        run: |
          export _NAME=$GOOS-$GOARCH
          export ASSET_NAME=$_NAME
          echo "GOOS: $GOOS, GOARCH: $GOARCH, GOARM: $GOARM, RELEASE_NAME: $_NAME"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_OUTPUT
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get project dependencies
        run: go mod download

      - name: Build V2RayAuto
        run: |
          mkdir -p build_assets
          go build -v -o build_assets/v2rayAuto -trimpath -ldflags "-s -w -buildid=" .

      - name: Rename Windows v2rayAuto
        if: matrix.goos == 'windows'
        run: |
          cd ./build_assets || exit 1
          mv v2rayAuto v2rayAuto.exe

      - name: Prepare package
        run: cp -v config.ini ./build_assets

      - name: Create ZIP archive
        run: |
          pushd build_assets || exit 1
          zip -9vr ../v2rayAuto-${{ steps.get_filename.outputs.ASSET_NAME }}.zip .
          popd || exit 1
          FILE=./v2rayAuto-${{ steps.get_filename.outputs.ASSET_NAME }}.zip
          DGST=$FILE.dgst
          openssl dgst -md5    $FILE | sed 's/([^)]*)//g' >>$DGST
          openssl dgst -sha1   $FILE | sed 's/([^)]*)//g' >>$DGST
          openssl dgst -sha256 $FILE | sed 's/([^)]*)//g' >>$DGST
          openssl dgst -sha512 $FILE | sed 's/([^)]*)//g' >>$DGST

      - name: Upload ZIP file to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: v2rayAuto-${{ steps.get_filename.outputs.ASSET_NAME }}.zip
          path: v2rayAuto-${{ steps.get_filename.outputs.ASSET_NAME }}.zip

      - name: Upload files to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./v2rayAuto-${{ steps.get_filename.outputs.ASSET_NAME }}.zip*
          tag: ${{ github.ref }}